name: Spring Boot + Flyway CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: "Welcome@1234$"
          MYSQL_DATABASE: flywaydb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -pWelcome@1234$"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Wait for MySQL to be ready
        run: |
          for i in `seq 1 30`; do
            echo "Waiting for MySQL..."
            mysql -h 127.0.0.1 -u root -p"Welcome@1234$" -e "SELECT 1" && break
            sleep 2
          done

      - name: Run Flyway migrations
        run: |
          mvn -B flyway:migrate \
            -Dflyway.url=jdbc:mysql://127.0.0.1:3306/flywaydb \
            -Dflyway.user=root \
            -Dflyway.password="Welcome@1234$"

      - name: Export Flyway schema history
        run: |
          docker exec ${{ job.services.mysql.id }} \
          mysqldump -uroot -p"Welcome@1234$" flywaydb flyway_schema_history > flyway_history.sql

      - name: Upload Flyway History Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flyway-history
          path: flyway_history.sql


      - name: Build the Spring Boot project
        run: mvn -B clean package -DskipTests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: target/*.jar
